# Generated by Django 3.2 on 2021-04-28 08:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_number', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_number', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=200)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('preference', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('looking', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('sold', 'SOLD'), ('unsold', 'UNSOLD')], max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.owner')),
                ('people', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.people')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=50)),
                ('type', models.CharField(choices=[('O', 'Owner'), ('P', 'PEOPLE')], max_length=50)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.owner')),
                ('people', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.people')),
            ],
        ),
    ]
