# Generated by Django 3.2 on 2021-04-28 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20210428_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.people'),
        ),
    ]
